    name: Model Training Pipeline

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11.5'
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
        - name: Run Jupyter Notebook
          run: |
            jupyter nbconvert --to notebook --execute notebooks/training-resnet50.ipynb